---
- hosts: all
  sudo: yes
  remote_user: vagrant

  vars:
    owner:             "apache"
    group:             "apache"
    httpd_conf:        "/etc/httpd/conf.d"
    var_root:          "/var/trac"
    wsgi_bin:          "{{var_root}}/cgi-bin"
    egg_cache:         "{{var_root}}/.python-eggs"
    trac_parent:       "{{var_root}}/projects"
    svn_parent:        "{{var_root}}/svn"
    git_parent:        "{{var_root}}/git"
    httpd_conf_parent: "{{var_root}}/httpd"

  tasks:
    - yum: name=subversion
    - yum: name=git
    - yum: name=patch
    - yum: name=httpd
    - yum: name=httpd-devel
    - yum: name=mod_wsgi
    - yum: name=mod_dav_svn
    - yum: name=python-pip 
    - yum: name=subversion-python
    - yum: name=gcc
    - yum: name=python-devel        # required by PIL which is required by TracBlockDiag
    - yum: name=zlib-devel          # required by PIL which is required by TracBlockDiag
    - yum: name=libjpeg-turbo-devel # required by PIL which is required by TracBlockDiag
    - yum: name=rubygem-asciidoctor
    - pip: name=Babel
    - pip: name=genshi                      version=0.6
    - pip: name=trac                        version=1.0
    - pip: name=TracBlockDiag               version=0.2.1
    - pip: name=TracAccountManager          version=0.4.4
    - pip: name=TracAutocompleteUsersPlugin version=0.4.3
    - name: TracXMLRPC
      command: sudo pip install 'svn+https://trac-hacks.org/svn/xmlrpcplugin/trunk' creates='/usr/lib/python2.7/site-packages/tracrpc'
    - name: TracJupyterNotebook
      command: sudo pip install 'svn+https://trac-hacks.org/svn/jupyternotebookplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracjupyternotebook'
    - name: TracCutomFieldAdmin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/customfieldadminplugin/0.11' creates='/usr/lib/python2.7/site-packages/customfieldadmin'
    - name: TracWysiwygPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracwysiwygplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracwysiwyg'
    - name: TracExcelDownloadPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/exceldownloadplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracexceldownload'
    - name: TracExportImportXlsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/exportimportxlsplugin/0.12' creates='/usr/lib/python2.7/site-packages/importexportxls'
    - name: TracDragDropPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracdragdropplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracdragdrop'
    - name: TracCiteCode
      command: sudo pip install 'svn+https://trac-hacks.org/svn/citecodemacro/1.0' creates='/usr/lib/python2.7/site-packages/traccitecode'
    - name: ReadmeRendererPlugin
      command: sudo pip install 'git+https://github.com/Southen/trac-readme-plugin.git' creates='/usr/lib/python2.7/site-packages/readme_renderer'
    - name: LogViewerPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/logviewerplugin/trunk' creates='/usr/lib/python2.7/site-packages/logviewer'
    - name: TracIniAdminPanelPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/traciniadminpanelplugin/trunk' creates='/usr/lib/python2.7/site-packages/inieditorpanel'
    - name: TracMermaid
      command: sudo pip install 'svn+https://trac-hacks.org/svn/mermaidmacro/1.0' creates='/usr/lib/python2.7/site-packages/tracmermaid'
    - name: SvnMultiUrlsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/svnmultiurlsplugin/0.12' creates='/usr/lib/python2.7/site-packages/svnmultiurls'
    - name: TracPerlPodPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/perlpodplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracperlpod'
    - name: TracSubcomponentsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/subcomponentsplugin/trunk' creates='/usr/lib/python2.7/site-packages/subcomponents'
    - name: TracAsciidoctorPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracasciidoctorplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracasciidoctor'
    - name: TracWikiGanttChartPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/wikiganttchartplugin/0.12' creates='/usr/lib/python2.7/site-packages/wikiganttchart'
    - name: pandoc
      script: install-pandoc.sh creates='/usr/local/bin/pandoc'
    - name: secure_path contains /usr/local/bin
      lineinfile: dest='/etc/sudoers' state=present regexp='^\s*#*\s*Defaults\s+secure_path\s*=' "line=Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"
    - name: TracPandoc
      command: sudo pip install 'svn+https://trac-hacks.org/svn/pandocplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracpandoc'
    - name: TicketStencil
      command: sudo pip install 'svn+https://trac-hacks.org/svn/ticketstencilplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracticketstencil'

    # Open LDAP
    - yum: name=openldap-servers
    - yum: name=openldap-clients
    - service: name=slapd state=started enabled=yes
    - command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif creates='/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}cosine.ldif'
    - command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif creates='/etc/openldap/slapd.d/cn=config/cn=schema/cn={2}inetorgperson.ldif'
    - copy: src=olcRootPW.ldif dest=/tmp/olcRootPW.ldif owner=root group=root mode=0600
    - command: ldapadd -Y EXTERNAL -H ldapi:// -f /tmp/olcRootPW.ldif
    # phpLDAPAdmin
    - yum: name=phpldapadmin
    - copy: src=phpldapadmin.conf dest=/etc/httpd/conf.d/phpldapadmin.conf owner=root group=root mode=0644
      notify: restart httpd
    # LDAPAcctMngrPlugin
    - pip: name=python-ldap
    - name: LDAPAcctMngrPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/ldapacctmngrplugin/trunk/ldapacctmngrplugin' creates='/usr/lib/python2.7/site-packages/securuty/ldapstore'

    - file: path={{svn_parent}}        state=directory owner={{owner}} group={{group}}
    - file: path={{git_parent}}        state=directory owner={{owner}} group={{group}}
    - file: path={{var_root}}          state=directory owner={{owner}} group={{group}}
    - file: path={{trac_parent}}       state=directory owner={{owner}} group={{group}}
    - file: path={{httpd_conf_parent}} state=directory owner={{owner}} group={{group}}
    - file: path={{wsgi_bin}}          state=directory owner={{owner}} group={{group}}
    - file: path={{egg_cache}}         state=directory owner={{owner}} group={{group}} mode=0777

    - copy:     src=svnindex.wsgi          dest={{wsgi_bin}}/svnindex.wsgi          owner={{owner}} group={{group}} mode=0755
      notify:   restart httpd
    - template: src=trac.wsgi              dest={{wsgi_bin}}/trac.wsgi              owner={{owner}} group={{group}} mode=0755
      notify:   restart httpd
    - template: src=trac.conf              dest={{httpd_conf}}/trac.conf
      notify:   restart httpd
    - template: src=create-trac-project.sh dest={{var_root}}/create-trac-project.sh owner={{owner}} group={{group}} mode=755
    - template: src=delete-trac-project.sh dest={{var_root}}/delete-trac-project.sh owner={{owner}} group={{group}} mode=755
    - file: path={{var_root}}/wiki/ja_JP state=directory owner={{owner}} group={{group}}
    - copy: src=wiki/ja_JP/default-pages dest={{var_root}}/wiki/ja_JP owner={{owner}} group={{group}}

    - service: name=httpd state=started enabled=yes
 
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
