---
- hosts: all
  sudo: yes

  vars:
    owner:             "apache"
    group:             "apache"
    httpd_conf:        "/etc/httpd/conf.d"
    var_root:          "/var/trac"
    wsgi_bin:          "{{var_root}}/cgi-bin"
    egg_cache:         "{{var_root}}/.python-eggs"
    trac_parent:       "{{var_root}}/projects"
    svn_parent:        "{{var_root}}/svn"
    git_parent:        "{{var_root}}/git"
    httpd_conf_parent: "{{var_root}}/httpd"
    rb_parent:         "{{var_root}}/rb"

  tasks:
    - yum: name=epel-release
    - yum: name=wget
    - yum: name=subversion
    - yum: name=git
    - yum: name=patch
    - yum: name=httpd
    - yum: name=httpd-devel
    - yum: name=mod_wsgi
    - yum: name=mod_dav_svn
    - yum: name=python-pip 
    - yum: name=subversion-python
    - yum: name=gcc
    - yum: name=python-devel        # required by PIL which is required by TracBlockDiag
    - yum: name=zlib-devel          # required by PIL which is required by TracBlockDiag
    - yum: name=libjpeg-turbo-devel # required by PIL which is required by TracBlockDiag
    - yum: name=rubygem-asciidoctor
    - pip: name=Babel                       version=0.9.6
    - pip: name=genshi                      version=0.6
    - pip: name=trac                        version=1.0
    - pip: name=TracBlockDiag               version=0.2.1
    - pip: name=TracAccountManager          version=0.4.4
    - pip: name=TracAutocompleteUsersPlugin version=0.4.3
    - pip: name=trac-github                 version=2.1.5
    - name: TracXMLRPC
      command: sudo pip install 'svn+https://trac-hacks.org/svn/xmlrpcplugin/trunk' creates='/usr/lib/python2.7/site-packages/tracrpc'
    - name: TracJupyterNotebook
      command: sudo pip install 'svn+https://trac-hacks.org/svn/jupyternotebookplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracjupyternotebook'
    - name: TracCutomFieldAdmin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/customfieldadminplugin/0.11' creates='/usr/lib/python2.7/site-packages/customfieldadmin'
    - name: TracWysiwygPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracwysiwygplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracwysiwyg'
    - name: TracExcelDownloadPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/exceldownloadplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracexceldownload'
    - name: TracExportImportXlsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/exportimportxlsplugin/0.12' creates='/usr/lib/python2.7/site-packages/importexportxls'
    - name: TracDragDropPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracdragdropplugin/0.12' creates='/usr/lib/python2.7/site-packages/tracdragdrop'
    - name: TracCiteCode
      command: sudo pip install 'svn+https://trac-hacks.org/svn/citecodemacro/1.0' creates='/usr/lib/python2.7/site-packages/traccitecode'
    - name: ReadmeRendererPlugin
      command: sudo pip install 'git+https://github.com/Southen/trac-readme-plugin.git' creates='/usr/lib/python2.7/site-packages/readme_renderer'
    - name: LogViewerPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/logviewerplugin/trunk' creates='/usr/lib/python2.7/site-packages/logviewer'
    - name: TracIniAdminPanelPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/traciniadminpanelplugin/trunk' creates='/usr/lib/python2.7/site-packages/inieditorpanel'
    - name: TracMermaid
      command: sudo pip install 'svn+https://trac-hacks.org/svn/mermaidmacro/1.0' creates='/usr/lib/python2.7/site-packages/tracmermaid'
    - name: SvnMultiUrlsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/svnmultiurlsplugin/0.12' creates='/usr/lib/python2.7/site-packages/svnmultiurls'
    - name: TracPerlPodPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/perlpodplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracperlpod'
    - name: TracSubcomponentsPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/subcomponentsplugin/trunk' creates='/usr/lib/python2.7/site-packages/subcomponents'
    - name: TracAsciidoctorPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/tracasciidoctorplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracasciidoctor'
    - name: TracWikiGanttChartPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/wikiganttchartplugin/0.12' creates='/usr/lib/python2.7/site-packages/wikiganttchart'
    - name: pandoc
      script: install-pandoc.sh creates='/usr/local/bin/pandoc'
    - name: secure_path contains /usr/local/bin
      lineinfile: dest='/etc/sudoers' state=present regexp='^\s*#*\s*Defaults\s+secure_path\s*=' "line=Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"
    - name: TracPandoc
      command: sudo pip install 'svn+https://trac-hacks.org/svn/pandocplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracpandoc'
    - name: TicketStencil
      command: sudo pip install 'svn+https://trac-hacks.org/svn/ticketstencilplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracticketstencil'
    - name: PdfPreview
      command: sudo pip install 'svn+https://trac-hacks.org/svn/pdfpreviewplugin/1.0' creates='/usr/lib/python2.7/site-packages/tracpdfpreview'

    # Open LDAP
    - yum: name=openldap-servers
    - yum: name=openldap-clients
    - service: name=slapd state=started enabled=yes
    - command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif creates='/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}cosine.ldif'
    - command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif creates='/etc/openldap/slapd.d/cn=config/cn=schema/cn={2}inetorgperson.ldif'
    - copy: src=olcRootPW.ldif dest=/usr/local/share/applications/olcRootPW.ldif owner=root group=root mode=0600
    - copy: src=init.ldif dest=/usr/local/share/applications/init.ldif owner=root group=root
    - copy: src=initldap.sh dest=/usr/local/sbin/initldap.sh owner=root group=root mode=0750
    # phpLDAPAdmin
    - yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    - yum: name=phpldapadmin enablerepo=remi-php56
    - copy: src=config.php dest=/etc/phpldapadmin/config.php owner=root group={{group}} mode=0640
    - copy: src=phpldapadmin.conf dest=/etc/httpd/conf.d/phpldapadmin.conf owner=root group=root mode=0644
      notify: restart httpd
    # LDAPAcctMngrPlugin
    - pip: name=python-ldap
    - name: LDAPAcctMngrPlugin
      command: sudo pip install 'svn+https://trac-hacks.org/svn/ldapacctmngrplugin/trunk/ldapacctmngrplugin' creates='/usr/lib/python2.7/site-packages/security/ldapstore.py'

    - file: path={{svn_parent}}        state=directory owner={{owner}} group={{group}}
    - file: path={{git_parent}}        state=directory owner={{owner}} group={{group}}
    - file: path={{var_root}}          state=directory owner={{owner}} group={{group}}
    - file: path={{trac_parent}}       state=directory owner={{owner}} group={{group}}
    - file: path={{httpd_conf_parent}} state=directory owner={{owner}} group={{group}}
    - file: path={{wsgi_bin}}          state=directory owner={{owner}} group={{group}}
    - file: path={{egg_cache}}         state=directory owner={{owner}} group={{group}} mode=0777

    - copy:     src=svnindex.wsgi          dest={{wsgi_bin}}/svnindex.wsgi          owner={{owner}} group={{group}} mode=0755
      notify:   restart httpd
    - template: src=trac.wsgi              dest={{wsgi_bin}}/trac.wsgi              owner={{owner}} group={{group}} mode=0755
      notify:   restart httpd
    - template: src=trac.conf              dest={{httpd_conf}}/trac.conf
      notify:   restart httpd
    - template: src=create-trac-project.sh dest=/usr/local/bin/create-trac-project.sh owner={{owner}} group={{group}} mode=750
    - template: src=delete-trac-project.sh dest=/usr/local/bin/delete-trac-project.sh owner={{owner}} group={{group}} mode=750
    - file: path={{var_root}}/wiki/ja_JP state=directory owner={{owner}} group={{group}}
    - copy: src=wiki/ja_JP/default-pages dest={{var_root}}/wiki/ja_JP owner={{owner}} group={{group}}

    # Review Board
    - template: src=create-rb-project.sh dest=/usr/local/sbin/create-rb-project.sh owner=root group=root mode=755
    - template: src=delete-rb-project.sh dest=/usr/local/sbin/delete-rb-project.sh owner=root group=root mode=755
    - file: path={{rb_parent}} state=directory owner={{owner}} group={{group}}
    - yum: name=memcached
    - yum: name=ReviewBoard

    # TestLink
    - yum: name=php-mysql enablerepo=remi-php56
    - yum: name=php enablerepo=remi-php56
    - yum: name=php-gd enablerepo=remi-php56
    - yum: name=php-mbstring enablerepo=remi-php56
    - template: src=MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo owner=root group=root
    - yum: name=MariaDB-server enablerepo=mariadb
    - yum: name=MariaDB-client enablerepo=mariadb
    - lineinfile: dest='/etc/php.ini' state=present regexp='^\s*session.gc_maxlifetime\s*=\s*' "line=session.gc_maxlifetime = 2400"
    - lineinfile: dest='/etc/php.ini' state=present regexp='^\s*max_execution_time\s*=\s*' "line=max_execution_time = 120"
    - script: install-testlink.sh creates='/var/www/html/testlink'
    - file: path=/var/www/html/testlink/gui/templates_c state=directory owner={{owner}} group={{group}} mode=0755 recurse=yes
    - file: path=/var/testlink
    - file: path=/var/testlink/logs
    - file: path=/var/testlink/upload_area
    - file: path=/var/testlink mode=0777
    - file: path=/var/www/html/testlink owner={{owner}} group={{group}}
    - service: name=mariadb state=started enabled=yes

    - service: name=httpd state=started enabled=yes
 
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
